# Generated by Django 4.2.7 on 2026-01-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_problem_submission_test_cases_passed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
