# Generated by Django 4.2.7 on 2026-01-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_topic_userprofile_branch_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('MEC', 'Mechanical Engineering'), ('CIV', 'Civil Engineering'), ('AI&DS', 'Artificial Intelligence and Data Science'), ('AIML', 'Artificial Intelligence and Machine Learning'), ('DS', 'Data Science'), ('CSBS', 'Computer Science and Business Systems')], max_length=10, null=True),
        ),
    ]
