# Generated by Django 4.2.7 on 2026-01-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_alter_userprofile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='points',
            field=models.IntegerField(default=10),
        ),
    ]
